# Bela Makefile

PROJECT = testing

BELA_DIR = /root/Bela


# Compiler and linker flags

CXXFLAGS += -I$(BELA_DIR)/include

LDLIBS=-lfftw3

# Source files

SOURCES = render.cpp

# Include Bela's Makefile rules

include $(BELA_DIR)/Makefile
